/* eslint-disable no-console -- CLI script that outputs to console */
/**
 * Type-check the test suite and gate against a per-file baseline.
 *
 * `tsconfig.test.json` is deliberately absent from the root `tsconfig.json`
 * references, so `pnpm run typecheck` (`tsgo -b`) never walks it. Wiring it in
 * directly would fail on a large pre-existing backlog, so this ratchet gates on
 * a checked-in baseline instead: the count per file may not move in either
 * direction without updating `test-type-baseline.json`.
 *
 * Retire this script once the baseline is empty: add
 * `{ "path": "./tsconfig.test.json" }` to the root references and delete both
 * this file and the baseline.
 *
 * Usage:
 *   pnpm run check:test-types
 *   pnpm run check:test-types -- --update   # rewrite the baseline
 *
 * Exit code 0 = baseline matches, 1 = drift (or the compiler failed to run).
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const BASELINE_PATH = join(import.meta.dirname, 'test-type-baseline.json');
const PROJECT = 'tsconfig.test.json';

export interface Baseline {
  readonly note: string;
  readonly total: number;
  readonly files: Record<string, number>;
}

const ERROR_LINE = /^(.+?)\((\d+),(\d+)\): error TS\d+:/;

/**
 * Count diagnostics per file. Multi-line errors indent their continuation
 * lines, so only lines matching the `path(line,col): error TSxxxx:` shape are
 * counted — an elaboration is part of the error above it, not a new one.
 */
export function parseDiagnostics(output: string): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const line of output.split('\n')) {
    const match = ERROR_LINE.exec(line);
    if (!match) continue;
    const file = match[1].replaceAll('\\', '/');
    counts[file] = (counts[file] ?? 0) + 1;
  }
  return counts;
}

/** Returns null for malformed JSON or a shape the ratchet can't compare against. */
export function readBaseline(raw: string): Baseline | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (typeof parsed !== 'object' || parsed === null) return null;
  const { total, files } = parsed as Partial<Baseline>;
  if (typeof total !== 'number') return null;
  if (typeof files !== 'object' || files === null) return null;
  if (Object.values(files).some((n) => typeof n !== 'number')) return null;
  return parsed as Baseline;
}

export interface Drift {
  readonly regressed: { file: string; from: number; to: number }[];
  readonly improved: { file: string; from: number; to: number }[];
  readonly appeared: { file: string; to: number }[];
  readonly cleared: { file: string; from: number }[];
}

export function diffAgainstBaseline(
  baseline: Record<string, number>,
  current: Record<string, number>
): Drift {
  const regressed: Drift['regressed'][number][] = [];
  const improved: Drift['improved'][number][] = [];
  const appeared: Drift['appeared'][number][] = [];
  const cleared: Drift['cleared'][number][] = [];

  for (const [file, to] of Object.entries(current)) {
    const from = baseline[file];
    if (from === undefined) appeared.push({ file, to });
    else if (to > from) regressed.push({ file, from, to });
    else if (to < from) improved.push({ file, from, to });
  }
  for (const [file, from] of Object.entries(baseline)) {
    if (current[file] === undefined) cleared.push({ file, from });
  }

  return { regressed, improved, appeared, cleared };
}

export function hasDrift(drift: Drift): boolean {
  return (
    drift.regressed.length > 0 ||
    drift.improved.length > 0 ||
    drift.appeared.length > 0 ||
    drift.cleared.length > 0
  );
}

function runCompiler(): string {
  try {
    execFileSync('pnpm', ['exec', 'tsgo', '-p', PROJECT, '--noEmit'], {
      cwd: ROOT,
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
    });
    return '';
  } catch (error) {
    const result = error as { stdout?: string; stderr?: string };
    return `${result.stdout ?? ''}\n${result.stderr ?? ''}`;
  }
}

function sortByCount(files: Record<string, number>): Record<string, number> {
  return Object.fromEntries(Object.entries(files).sort(([a], [b]) => a.localeCompare(b)));
}

function main(): void {
  const update = process.argv.includes('--update');
  const output = runCompiler();
  const current = parseDiagnostics(output);
  const total = Object.values(current).reduce((sum, n) => sum + n, 0);

  // A compiler crash produces output with no parseable diagnostics. Without
  // this guard the gate would read that as "zero errors" and pass vacuously.
  if (total === 0 && output.trim() !== '') {
    console.error(`✗ tsgo produced no parseable diagnostics but did not exit clean:\n${output}`);
    process.exit(1);
  }

  if (update) {
    const baseline: Baseline = {
      note: 'Per-file type errors under tsconfig.test.json. Generated by scripts/check-test-types.ts --update. This number must only go down.',
      total,
      files: sortByCount(current),
    };
    writeFileSync(BASELINE_PATH, `${JSON.stringify(baseline, null, 2)}\n`);
    console.log(`✓ Baseline updated: ${total} errors across ${Object.keys(current).length} files`);
    return;
  }

  if (!existsSync(BASELINE_PATH)) {
    console.error(
      `✗ Missing baseline at ${BASELINE_PATH}. Run: pnpm run check:test-types -- --update`
    );
    process.exit(1);
  }

  const baseline = readBaseline(readFileSync(BASELINE_PATH, 'utf8'));
  if (baseline === null) {
    console.error(
      `✗ Baseline at ${BASELINE_PATH} is unreadable — expected { total: number, files: Record<string, number> }.\n` +
        '  Restore it from git, or regenerate with: pnpm run check:test-types -- --update'
    );
    process.exit(1);
  }

  const drift = diffAgainstBaseline(baseline.files, current);

  if (!hasDrift(drift)) {
    console.log(
      `✓ Test types match baseline (${total} known errors, ${Object.keys(current).length} files)`
    );
    return;
  }

  if (drift.appeared.length > 0) {
    console.error('\n✗ Test files that newly fail to type-check:');
    for (const { file, to } of drift.appeared) console.error(`    ${file} (${to})`);
  }
  if (drift.regressed.length > 0) {
    console.error('\n✗ Test files with more type errors than the baseline:');
    for (const { file, from, to } of drift.regressed)
      console.error(`    ${file} (${from} → ${to})`);
  }
  if (drift.improved.length > 0 || drift.cleared.length > 0) {
    console.error('\n→ Progress! Lock it in with: pnpm run check:test-types -- --update');
    for (const { file, from, to } of drift.improved) console.error(`    ${file} (${from} → ${to})`);
    for (const { file, from } of drift.cleared) console.error(`    ${file} (${from} → 0)`);
  }

  console.error(`\nBaseline total ${baseline.total} → current ${total}`);
  console.error('Run `pnpm exec tsgo -p tsconfig.test.json --noEmit` to see the errors.\n');
  process.exit(1);
}

const isDirectExecution = process.argv[1]?.endsWith('check-test-types.ts');
if (isDirectExecution) main();
