/**
 * Human-readable, per-locale display terms for the vocabulary catalog.
 *
 * Two jobs: fix the acronym mangling of the alias-derived fallback (the
 * first-alias rule turns `battery_aa` into "Aa", `usb_cable` into "Usb"), and
 * let catalog suggestions display — and insert — in the user's language. Keys
 * are locale codes; a missing locale falls back to `en`, then to the alias
 * fallback in `getDisplayTerm`. Locale is typed as a plain string here so this
 * telemetry-adjacent module stays decoupled from the i18n layer. Brand/acronym
 * terms (Arduino, LED) are intentionally identical across locales.
 */
export const CATALOG_DISPLAY: Record<string, Record<string, string>> = {
  allen_key: {
    en: 'Allen key',
    de: 'Inbusschlüssel',
    es: 'Llave Allen',
    fr: 'Clé Allen',
    it: 'Chiave a brugola',
    nl: 'Inbussleutel',
    'pt-BR': 'Chave Allen',
    ja: '六角レンチ',
    nb: 'Unbrakonøkkel',
    sv: 'Insexnyckel',
    uk: 'Шестигранний ключ',
  },
  arduino: {
    en: 'Arduino',
    de: 'Arduino',
    es: 'Arduino',
    fr: 'Arduino',
    it: 'Arduino',
    nl: 'Arduino',
    'pt-BR': 'Arduino',
    ja: 'Arduino',
    nb: 'Arduino',
    sv: 'Arduino',
    uk: 'Arduino',
  },
  battery_aa: {
    en: 'AA battery',
    de: 'AA-Batterie',
    es: 'Pila AA',
    fr: 'Pile AA',
    it: 'Pila AA',
    nl: 'AA-batterij',
    'pt-BR': 'Pilha AA',
    ja: '単3電池',
    nb: 'AA-batteri',
    sv: 'AA-batteri',
    uk: 'Батарейка AA',
  },
  battery_aaa: {
    en: 'AAA battery',
    de: 'AAA-Batterie',
    es: 'Pila AAA',
    fr: 'Pile AAA',
    it: 'Pila AAA',
    nl: 'AAA-batterij',
    'pt-BR': 'Pilha AAA',
    ja: '単4電池',
    nb: 'AAA-batteri',
    sv: 'AAA-batteri',
    uk: 'Батарейка AAA',
  },
  bearing: {
    en: 'Bearing',
    de: 'Kugellager',
    es: 'Rodamiento',
    fr: 'Roulement',
    it: 'Cuscinetto',
    nl: 'Kogellager',
    'pt-BR': 'Rolamento',
    ja: 'ベアリング',
    nb: 'Kulelager',
    sv: 'Kullager',
    uk: 'Підшипник',
  },
  bolt: {
    en: 'Bolt',
    de: 'Bolzen',
    es: 'Perno',
    fr: 'Boulon',
    it: 'Bullone',
    nl: 'Bout',
    'pt-BR': 'Perno',
    ja: 'ボルト',
    nb: 'Bolt',
    sv: 'Bult',
    uk: 'Болт',
  },
  brush: {
    en: 'Brush',
    de: 'Pinsel',
    es: 'Pincel',
    fr: 'Pinceau',
    it: 'Pennello',
    nl: 'Kwast',
    'pt-BR': 'Pincel',
    ja: '筆',
    nb: 'Pensel',
    sv: 'Pensel',
    uk: 'Пензлик',
  },
  capacitor: {
    en: 'Capacitor',
    de: 'Kondensator',
    es: 'Condensador',
    fr: 'Condensateur',
    it: 'Condensatore',
    nl: 'Condensator',
    'pt-BR': 'Capacitor',
    ja: 'コンデンサ',
    nb: 'Kondensator',
    sv: 'Kondensator',
    uk: 'Конденсатор',
  },
  clip: {
    en: 'Clip',
    de: 'Klammer',
    es: 'Clip',
    fr: 'Clip',
    it: 'Clip',
    nl: 'Clip',
    'pt-BR': 'Clipe',
    ja: 'クリップ',
    nb: 'Klips',
    sv: 'Clips',
    uk: 'Затискач',
  },
  coin: {
    en: 'Coin',
    de: 'Münze',
    es: 'Moneda',
    fr: 'Pièce',
    it: 'Moneta',
    nl: 'Munt',
    'pt-BR': 'Moeda',
    ja: 'コイン',
    nb: 'Mynt',
    sv: 'Mynt',
    uk: 'Монета',
  },
  drill_bit: {
    en: 'Drill bit',
    de: 'Bohrer',
    es: 'Broca',
    fr: 'Foret',
    it: 'Punta da trapano',
    nl: 'Boor',
    'pt-BR': 'Broca',
    ja: 'ドリルビット',
    nb: 'Bor',
    sv: 'Borr',
    uk: 'Свердло',
  },
  filament_sample: {
    en: 'Filament sample',
    de: 'Filamentmuster',
    es: 'Muestra de filamento',
    fr: 'Échantillon de filament',
    it: 'Campione di filamento',
    nl: 'Filamentmonster',
    'pt-BR': 'Amostra de filamento',
    ja: 'フィラメントサンプル',
    nb: 'Filamentprøve',
    sv: 'Filamentprov',
    uk: 'Зразок філаменту',
  },
  flashlight: {
    en: 'Flashlight',
    de: 'Taschenlampe',
    es: 'Linterna',
    fr: 'Lampe de poche',
    it: 'Torcia',
    nl: 'Zaklamp',
    'pt-BR': 'Lanterna',
    ja: '懐中電灯',
    nb: 'Lommelykt',
    sv: 'Ficklampa',
    uk: 'Ліхтарик',
  },
  glasses: {
    en: 'Glasses',
    de: 'Brille',
    es: 'Gafas',
    fr: 'Lunettes',
    it: 'Occhiali',
    nl: 'Bril',
    'pt-BR': 'Óculos',
    ja: 'メガネ',
    nb: 'Briller',
    sv: 'Glasögon',
    uk: 'Окуляри',
  },
  glue: {
    en: 'Glue',
    de: 'Kleber',
    es: 'Pegamento',
    fr: 'Colle',
    it: 'Colla',
    nl: 'Lijm',
    'pt-BR': 'Cola',
    ja: '接着剤',
    nb: 'Lim',
    sv: 'Lim',
    uk: 'Клей',
  },
  hammer: {
    en: 'Hammer',
    de: 'Hammer',
    es: 'Martillo',
    fr: 'Marteau',
    it: 'Martello',
    nl: 'Hamer',
    'pt-BR': 'Martelo',
    ja: 'ハンマー',
    nb: 'Hammer',
    sv: 'Hammare',
    uk: 'Молоток',
  },
  heat_insert: {
    en: 'Heat insert',
    de: 'Gewindeeinsatz',
    es: 'Inserto roscado',
    fr: 'Insert fileté',
    it: 'Inserto filettato',
    nl: 'Draadinsert',
    'pt-BR': 'Inserto roscado',
    ja: 'インサートナット',
    nb: 'Gjengeinnsats',
    sv: 'Gänginsats',
    uk: 'Різьбова вставка',
  },
  jewelry: {
    en: 'Jewelry',
    de: 'Schmuck',
    es: 'Joyería',
    fr: 'Bijoux',
    it: 'Gioielli',
    nl: 'Sieraden',
    'pt-BR': 'Joias',
    ja: 'アクセサリー',
    nb: 'Smykker',
    sv: 'Smycken',
    uk: 'Прикраси',
  },
  key: {
    en: 'Key',
    de: 'Schlüssel',
    es: 'Llave',
    fr: 'Clé',
    it: 'Chiave',
    nl: 'Sleutel',
    'pt-BR': 'Chave',
    ja: '鍵',
    nb: 'Nøkkel',
    sv: 'Nyckel',
    uk: 'Ключ',
  },
  knife: {
    en: 'Knife',
    de: 'Messer',
    es: 'Cuchillo',
    fr: 'Couteau',
    it: 'Coltello',
    nl: 'Mes',
    'pt-BR': 'Faca',
    ja: 'ナイフ',
    nb: 'Kniv',
    sv: 'Kniv',
    uk: 'Ніж',
  },
  led: {
    en: 'LED',
    de: 'LED',
    es: 'LED',
    fr: 'LED',
    it: 'LED',
    nl: 'LED',
    'pt-BR': 'LED',
    ja: 'LED',
    nb: 'LED',
    sv: 'LED',
    uk: 'LED',
  },
  magnet: {
    en: 'Magnet',
    de: 'Magnet',
    es: 'Imán',
    fr: 'Aimant',
    it: 'Magnete',
    nl: 'Magneet',
    'pt-BR': 'Ímã',
    ja: '磁石',
    nb: 'Magnet',
    sv: 'Magnet',
    uk: 'Магніт',
  },
  medication: {
    en: 'Medication',
    de: 'Medikament',
    es: 'Medicamento',
    fr: 'Médicament',
    it: 'Medicinale',
    nl: 'Medicijn',
    'pt-BR': 'Remédio',
    ja: '薬',
    nb: 'Medisin',
    sv: 'Medicin',
    uk: 'Ліки',
  },
  nail: {
    en: 'Nail',
    de: 'Nagel',
    es: 'Clavo',
    fr: 'Clou',
    it: 'Chiodo',
    nl: 'Spijker',
    'pt-BR': 'Prego',
    ja: '釘',
    nb: 'Spiker',
    sv: 'Spik',
    uk: 'Цвях',
  },
  nozzle: {
    en: 'Nozzle',
    de: 'Düse',
    es: 'Boquilla',
    fr: 'Buse',
    it: 'Ugello',
    nl: 'Nozzle',
    'pt-BR': 'Bico',
    ja: 'ノズル',
    nb: 'Dyse',
    sv: 'Munstycke',
    uk: 'Сопло',
  },
  nut: {
    en: 'Nut',
    de: 'Mutter',
    es: 'Tuerca',
    fr: 'Écrou',
    it: 'Dado',
    nl: 'Moer',
    'pt-BR': 'Porca',
    ja: 'ナット',
    nb: 'Mutter',
    sv: 'Mutter',
    uk: 'Гайка',
  },
  paint: {
    en: 'Paint',
    de: 'Farbe',
    es: 'Pintura',
    fr: 'Peinture',
    it: 'Vernice',
    nl: 'Verf',
    'pt-BR': 'Tinta',
    ja: '塗料',
    nb: 'Maling',
    sv: 'Färg',
    uk: 'Фарба',
  },
  pen: {
    en: 'Pen',
    de: 'Stift',
    es: 'Bolígrafo',
    fr: 'Stylo',
    it: 'Penna',
    nl: 'Pen',
    'pt-BR': 'Caneta',
    ja: 'ペン',
    nb: 'Penn',
    sv: 'Penna',
    uk: 'Ручка',
  },
  pliers: {
    en: 'Pliers',
    de: 'Zange',
    es: 'Alicates',
    fr: 'Pince',
    it: 'Pinza',
    nl: 'Tang',
    'pt-BR': 'Alicate',
    ja: 'ペンチ',
    nb: 'Tang',
    sv: 'Tång',
    uk: 'Плоскогубці',
  },
  resistor: {
    en: 'Resistor',
    de: 'Widerstand',
    es: 'Resistencia',
    fr: 'Résistance',
    it: 'Resistenza',
    nl: 'Weerstand',
    'pt-BR': 'Resistor',
    ja: '抵抗',
    nb: 'Motstand',
    sv: 'Motstånd',
    uk: 'Резистор',
  },
  scissors: {
    en: 'Scissors',
    de: 'Schere',
    es: 'Tijeras',
    fr: 'Ciseaux',
    it: 'Forbici',
    nl: 'Schaar',
    'pt-BR': 'Tesoura',
    ja: 'はさみ',
    nb: 'Saks',
    sv: 'Sax',
    uk: 'Ножиці',
  },
  screw: {
    en: 'Screw',
    de: 'Schraube',
    es: 'Tornillo',
    fr: 'Vis',
    it: 'Vite',
    nl: 'Schroef',
    'pt-BR': 'Parafuso',
    ja: 'ネジ',
    nb: 'Skrue',
    sv: 'Skruv',
    uk: 'Гвинт',
  },
  screwdriver: {
    en: 'Screwdriver',
    de: 'Schraubendreher',
    es: 'Destornillador',
    fr: 'Tournevis',
    it: 'Cacciavite',
    nl: 'Schroevendraaier',
    'pt-BR': 'Chave de fenda',
    ja: 'ドライバー',
    nb: 'Skrutrekker',
    sv: 'Skruvmejsel',
    uk: 'Викрутка',
  },
  sd_card: {
    en: 'SD card',
    de: 'SD-Karte',
    es: 'Tarjeta SD',
    fr: 'Carte SD',
    it: 'Scheda SD',
    nl: 'SD-kaart',
    'pt-BR': 'Cartão SD',
    ja: 'SDカード',
    nb: 'SD-kort',
    sv: 'SD-kort',
    uk: 'SD-карта',
  },
  tape: {
    en: 'Tape',
    de: 'Klebeband',
    es: 'Cinta adhesiva',
    fr: 'Ruban adhésif',
    it: 'Nastro adesivo',
    nl: 'Plakband',
    'pt-BR': 'Fita adesiva',
    ja: 'テープ',
    nb: 'Teip',
    sv: 'Tejp',
    uk: 'Скотч',
  },
  tape_measure: {
    en: 'Tape measure',
    de: 'Maßband',
    es: 'Cinta métrica',
    fr: 'Mètre ruban',
    it: 'Metro a nastro',
    nl: 'Rolmaat',
    'pt-BR': 'Trena',
    ja: 'メジャー',
    nb: 'Målebånd',
    sv: 'Måttband',
    uk: 'Рулетка',
  },
  usb_cable: {
    en: 'USB cable',
    de: 'USB-Kabel',
    es: 'Cable USB',
    fr: 'Câble USB',
    it: 'Cavo USB',
    nl: 'USB-kabel',
    'pt-BR': 'Cabo USB',
    ja: 'USBケーブル',
    nb: 'USB-kabel',
    sv: 'USB-kabel',
    uk: 'USB-кабель',
  },
  washer: {
    en: 'Washer',
    de: 'Unterlegscheibe',
    es: 'Arandela',
    fr: 'Rondelle',
    it: 'Rondella',
    nl: 'Sluitring',
    'pt-BR': 'Arruela',
    ja: 'ワッシャー',
    nb: 'Skive',
    sv: 'Bricka',
    uk: 'Шайба',
  },
  watch: {
    en: 'Watch',
    de: 'Uhr',
    es: 'Reloj',
    fr: 'Montre',
    it: 'Orologio',
    nl: 'Horloge',
    'pt-BR': 'Relógio',
    ja: '腕時計',
    nb: 'Klokke',
    sv: 'Klocka',
    uk: 'Годинник',
  },
  wire: {
    en: 'Wire',
    de: 'Draht',
    es: 'Cable',
    fr: 'Fil',
    it: 'Filo',
    nl: 'Draad',
    'pt-BR': 'Fio',
    ja: 'ワイヤー',
    nb: 'Ledning',
    sv: 'Tråd',
    uk: 'Дріт',
  },
  wrench: {
    en: 'Wrench',
    de: 'Schraubenschlüssel',
    es: 'Llave inglesa',
    fr: 'Clé à molette',
    it: 'Chiave inglese',
    nl: 'Moersleutel',
    'pt-BR': 'Chave inglesa',
    ja: 'レンチ',
    nb: 'Skiftenøkkel',
    sv: 'Skiftnyckel',
    uk: 'Гайковий ключ',
  },
};
